name: "Hello World"
description: "Prints hello world"
inputs:
  owner:
    description: "Owner of the repository if it is not the current one"
    required: true
  repo:
    description: "Repository on which to udpate. Used only if you want to udpate on another repo"
    required: true
  imageTag:
    description: "The tag of the image to be udpated"
    required: true
  githubToken:
    description: GitHub Token
    required: true
outputs:
  branchName:
    description: "The Branch Name of the created branch"
  branchUrl:
    description: "The URL users can navigate to in order to view the branch"
  pullRequestUrl:
    description: "The URL users can navigate to in order to view the pull request"

runs:
  using: "node20"
  main: "index.js"
