name: Test Action

on:
  # pull_request:
  # types: [labeled]
  push:
    # branches:
    #   - dev
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Hello world action step
        uses: ./
        id: hello
        with:
          owner: 5h4k4r
          repo: pilgrimage-gitops-shakar
          imageTag: "v1.0.0"
          githubToken: ${{ secrets.PAT_TOKEN }}
