name: Test Action

on:
  # pull_request:
  # types: [labeled]
  push:
    # branches:
    #   - dev
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.PGP_PRIVATE_KEY }}
          passphrase: ${{ secrets.PGP_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Hello world action step
        uses: ./
        id: hello
        with:
          owner: 5h4k4r
          repo: pilgrimage-gitops-shakar
          imageTag: "v1.0.0"
          githubToken: ${{ secrets.PAT_TOKEN }}
